/**
 * src/runtime/transcriptLog.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * The spoken record of one call — CALLER and AGENT lines in the order they
 * happened. Data only: nothing here is parsed, and nothing here can
 * influence what the agent decides.
 *
 * The caller-line correlation is PORTED VERBATIM (twice now: this repo's
 * production ticketing adapter -> 5Star -> here), where a live call proved
 * and a long review cycle refined its rules:
 *
 *   Grok re-emits `conversation.item.input_audio_transcription.completed`
 *   for the same caller turn as speech continues — each event carrying the
 *   cumulative transcript so far, corrections included. Appended naively,
 *   every caller sentence lands in the record up to five times.
 *
 *   - Which emissions are the same utterance is decided by the wire's own
 *     item identity when both sides carry an item_id, and by a WORD-level
 *     refinement heuristic when they do not (character prefixes merge
 *     "No." into "Not before noon." on a coincidence of letters).
 *   - A speech boundary (VAD speech_started while a line is open) does not
 *     close the line — VAD segments one utterance — but after one, only a
 *     pure EXTENSION still merges: it carries every earlier word and can
 *     lose nothing, while a shorter word-prefix may be a NEW statement and
 *     a tail revision may be a CHANGED answer. Both append.
 *   - The bias is deliberate everywhere: a near-duplicate line is
 *     cosmetic; an overwritten answer is lost caller data.
 *
 * The one difference from the scheduling port: there, an AGENT line was the
 * renderer's own scripted text, known before it was spoken. Here MOST of the
 * agent's words are generated by the model, so the text arrives on the wire
 * as the utterance's transcript — see mediaStreamBridge.ts.
 *
 * The GREETING is the exception that behaves like the scheduling port: it is
 * scripted, so its words are known before the model produces them and its
 * line is written the moment its audio starts playing — by `openingLine`,
 * which differs from `agentLine` in two ways, both consequences of writing a
 * line before its delivery is proved: it does not close the open caller turn,
 * and it hands back the index it wrote so a greeting the call cuts short can
 * be amended in place rather than recorded a second time. Beyond that the log
 * does not care where an agent line came from.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Casing/punctuation-tolerant word normalization. */
export function normalizeSpokenText(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

/** Normalized-word edit-distance similarity, 0..1, for the tail-revision
 * check below. Words are short; the quadratic cost is trivial. */
function wordSimilarity(a: string, b: string): number {
  if (a === b) return 1;
  const dist: number[] = Array.from({ length: b.length + 1 }, (_, j) => j);
  for (let i = 1; i <= a.length; i += 1) {
    let prevDiag = dist[0];
    dist[0] = i;
    for (let j = 1; j <= b.length; j += 1) {
      const tmp = dist[j];
      dist[j] = Math.min(dist[j] + 1, dist[j - 1] + 1, prevDiag + (a[i - 1] === b[j - 1] ? 0 : 1));
      prevDiag = tmp;
    }
  }
  const maxLen = Math.max(a.length, b.length);
  return maxLen === 0 ? 1 : 1 - dist[b.length] / maxLen;
}

/** What a new completion does to the open caller line, judged WORD by
 * word. A cumulative re-emission keeps every earlier word intact, so:
 *  - open line's words leading the new text → 'extend' (it grew or is
 *    identical — replacing can lose nothing);
 *  - new text a strict word-prefix of the open line → 'keep' (a shorter
 *    re-emission; replacing would truncate what the caller said);
 *  - same word count, at least one leading word shared, only the final
 *    word differing AND the final words near-neighbors → 'revise' (an ASR
 *    tail revision: "October 4, 1984." → "October 4, 1985."), while a new
 *    answer reusing the sentence frame does not ("I need frames." → "I
 *    need lenses."); one-word pairs have no shared frame and never take
 *    this branch ("Cash." → "Card.");
 *  - anything else → 'append'.
 * 'extend' and 'revise' are distinguished so a speech boundary can treat
 * them differently: an extension can never lose content; a revision after
 * a boundary is just as likely a CHANGED answer and must append. */
function refinementVerdict(prev: string, next: string): "extend" | "revise" | "keep" | "append" {
  const a = prev.split(/\s+/).map(normalizeSpokenText).filter(Boolean);
  const b = next.split(/\s+/).map(normalizeSpokenText).filter(Boolean);
  if (!a.length || !b.length) return "append";
  const min = Math.min(a.length, b.length);
  let shared = 0;
  while (shared < min && a[shared] === b[shared]) shared += 1;
  if (shared === a.length) return "extend";
  if (shared === b.length) return "keep";
  if (a.length === b.length && shared === a.length - 1 && shared >= 1) {
    return wordSimilarity(a[a.length - 1], b[b.length - 1]) >= 0.5 ? "revise" : "append";
  }
  return "append";
}

export class CallTranscriptLog {
  /** Ordered lines of the call: `CALLER: …` / `AGENT: …`. */
  readonly lines: string[] = [];

  private openCallerLine: {
    index: number;
    text: string;
    itemId: string | null;
    boundaryCrossed: boolean;
  } | null = null;

  /** One caller transcription completion — cumulative per turn, possibly
   * re-emitted many times (see module doc). */
  callerCompleted(text: string, itemId?: string): void {
    if (!text) return;
    const open = this.openCallerLine;
    let verdict: "replace" | "keep" | "append";
    if (!open) {
      verdict = "append";
    } else if (open.itemId && itemId) {
      verdict = open.itemId === itemId ? "replace" : "append";
    } else {
      const refinement = refinementVerdict(open.text, text);
      verdict =
        refinement === "extend"
          ? "replace"
          : refinement === "revise"
            ? open.boundaryCrossed
              ? "append"
              : "replace"
            : refinement === "keep"
              ? open.boundaryCrossed
                ? "append"
                : "keep"
              : "append";
    }
    if (verdict === "replace" && open) {
      open.text = text;
      if (itemId) open.itemId = itemId;
      // A replace proves the utterance continued across the boundary.
      open.boundaryCrossed = false;
      this.lines[open.index] = `CALLER: ${text}`;
    } else if (verdict === "append") {
      this.openCallerLine = {
        index: this.lines.length,
        text,
        itemId: itemId ?? null,
        boundaryCrossed: false,
      };
      this.lines.push(`CALLER: ${text}`);
    }
    // 'keep': a shorter re-emission — the fuller line stays as-is.
  }

  /** VAD speech_started while a caller line is open: remember the
   * boundary. It does NOT close the line — VAD segments one utterance —
   * it only disarms the verdicts that could discard or overwrite text. */
  callerBoundary(): void {
    if (this.openCallerLine) this.openCallerLine.boundaryCrossed = true;
  }

  /** One agent utterance (the renderer's exact text). An agent line means
   * the provider moved on: the open caller turn closes. */
  agentLine(text: string): void {
    this.openCallerLine = null;
    this.lines.push(`AGENT: ${text}`);
  }

  /**
   * The scripted opening, written when its audio starts playing.
   *
   * Everything `agentLine` does EXCEPT closing the open caller turn, and the
   * exception is the point. The greeting was queued at the handshake, before
   * the caller had said anything, so it is not the provider moving on from
   * their turn. Closing it strands a caller utterance that straddles the
   * moment playback began: their ASR is cumulative, so the next re-emission
   * is the SAME turn, and against a closed line it appends instead of
   * replacing — the caller's words landing twice, once on each side of the
   * opening. That is the duplication PR #241 fought, in a narrower window
   * (Codex, #243).
   *
   * Their line stays open and keeps refining in place, at the position where
   * their turn began, which is ahead of the greeting exactly when they
   * started speaking first. That window is not open-ended: whoever settles
   * this line — its mark echo, or the cut that ends it — calls
   * `closeCallerTurn`.
   *
   * Returns the index of the line written, which only `amendAgentLine` needs. */
  openingLine(text: string): number {
    this.lines.push(`AGENT: ${text}`);
    return this.lines.length - 1;
  }

  /** Rewrite an agent line already in the record, and close the caller turn.
   *
   * Only a line written BEFORE its playback was proved can need this, which
   * on this runtime means only the greeting. When the call cuts that audio
   * short the record has to say so, and appending would report the same words
   * twice — once whole, once interrupted. Rewriting in place cannot disturb
   * the open caller line's index, because no line moves.
   *
   * The turn closes here for the same reason it closes in `agentLine`: an
   * amendment is that line FINISHING, cut short rather than delivered, and a
   * finished agent line means the provider moved on. `openingLine` is the
   * only one that leaves the turn open, and only for as long as its audio is
   * still playing. */
  amendAgentLine(index: number, text: string): void {
    if (index < 0 || index >= this.lines.length) return;
    this.lines[index] = `AGENT: ${text}`;
    this.closeCallerTurn();
  }

  /**
   * The open caller turn is over, with no agent line to write for it.
   *
   * One rule, four ways of reaching it. `agentLine` and `amendAgentLine`
   * close the turn themselves, because each is an agent line FINISHED — one
   * delivered, one cut short — and a finished agent line means the provider
   * moved on. `openingLine` is the exception, and only while its audio is
   * still playing. This method is the fourth case: that opening line
   * finished by being DELIVERED, proved by its mark echo, with nothing to
   * rewrite.
   *
   * Leaving it open lets a genuinely NEW utterance merge backwards into the
   * one before the greeting. An EXTENSION replaces even across a speech
   * boundary, by design: within one turn it carries every earlier word and
   * can lose nothing. Across a finished agent line it can — "yes", then "yes
   * this is Wayne" after the greeting, becomes one line reading as if all of
   * it were said before the practice ever spoke (Codex, #243). */
  closeCallerTurn(): void {
    this.openCallerLine = null;
  }

  /** Call over — nothing more can refine the open line. */
  close(): void {
    this.closeCallerTurn();
  }

  render(): string {
    return this.lines.join("\n");
  }
}
